/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package APW_ParkingGarageApp;


import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 * This is a Graphic User Interface GUI class. Used to represent the entry terminal of a Parking Garage.
 * @author andre_000
 */
public class InTerminalGUI extends javax.swing.JFrame {
    private InTerminal inComp = new InTerminal();

    /**
     * Getter for the InTerminal inComp Property.
     * @return InTerminal
     */
    public final InTerminal getInComp() {
        return inComp;
    }

    /**
     * Setter for InTerminal inComp property.
     * @param inComp InTerminal
     */
    public final void setInComp(InTerminal inComp) {
        this.inComp = inComp;
    }
    
    /**
     * Getter for the Parking lot List of Cars. It calls the inComp's getter method.
     * @return List
     */
    public final List getParkingLotCarList(){
        return inComp.getParkingLotCarList();
    }
    
    /**
     * Setter for the Parking Lot List of Car Objects. 
     * It sets the carListCB ComboBox by call the getparkingLotCarList property.
     */
    public final void setParkingLotCarList(){
        carListCB.setModel(new DefaultComboBoxModel(this.getParkingLotCarList().toArray()));
    }
    /**
     * unPark Car Method, calls inComps unparkCar method.
     * @param car Car
     */
    public final void unparkCar(Car car){
        inComp.unparkCar(car);
    }
     
    /**
     * Creates new form INGUI and sets the inComp property.
     * @param inComp InTerminal
     */
    public InTerminalGUI(InTerminal inComp) {
        this.inComp = inComp;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParkButton = new javax.swing.JButton();
        WelcomLabel = new javax.swing.JLabel();
        carListCB = new javax.swing.JComboBox();
        toOutTerminalGUIButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ParkButton.setText("Park a Car");
        ParkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParkButtonActionPerformed(evt);
            }
        });

        WelcomLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        WelcomLabel.setText("Welcome to the garage");

        toOutTerminalGUIButton.setText("To Out Terminal");
        toOutTerminalGUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toOutTerminalGUIButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toOutTerminalGUIButton, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(WelcomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(ParkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carListCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(carListCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ParkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(toOutTerminalGUIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Creates a Car object then passes it to the inComp's parkNewCar method.
     * resets the carListCB ComboBox
     * @param evt 
     */
    private void ParkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParkButtonActionPerformed
        
        Car car1 = new Car();
        inComp.parkNewCar(car1);
        setParkingLotCarList();
    }//GEN-LAST:event_ParkButtonActionPerformed
    /**
     * Creates the outTerminal GUI and passes itself to it.
     * @param evt 
     */
    private void toOutTerminalGUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toOutTerminalGUIButtonActionPerformed
        
              java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new OutTerminalGUI(this).setVisible(true);
            }
        });
        new OutTerminalGUI(this).setVisible(true);
        
    }//GEN-LAST:event_toOutTerminalGUIButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ParkButton;
    private javax.swing.JLabel WelcomLabel;
    private javax.swing.JComboBox carListCB;
    private javax.swing.JButton toOutTerminalGUIButton;
    // End of variables declaration//GEN-END:variables
}
