/*
 * To change this license header, choose License Headers inTerminalGUI Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template inTerminalGUI the editor.
 */
package APW_ParkingGarageApp;

import javax.swing.DefaultComboBoxModel;
import java.util.ArrayList;
/**
 *
 * @author andre_000
 */
public class OutTerminalGUI extends javax.swing.JFrame {
    InTerminalGUI inTerminalGUI;
    JOptionPaneOutput alertWindow = new JOptionPaneOutput();
    
    
    /**
     * Creates new form OUTGUI
     */
    public OutTerminalGUI(InTerminalGUI INGUI) {
        this.inTerminalGUI = INGUI;
        inTerminalGUI.setVisible(false);
        initComponents();
        CbCarList.setModel(new DefaultComboBoxModel(inTerminalGUI.getParkingLotCarList().toArray()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CbCarList = new javax.swing.JComboBox();
        btnUnpark = new javax.swing.JButton();
        btnBacktoInTerminalGUI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CbCarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbCarListActionPerformed(evt);
            }
        });

        btnUnpark.setText("Unpark a Car");
        btnUnpark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnparkActionPerformed(evt);
            }
        });

        btnBacktoInTerminalGUI.setText("Back to Entry Screen");
        btnBacktoInTerminalGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktoInTerminalGUIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(CbCarList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnBacktoInTerminalGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnUnpark, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(CbCarList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnUnpark, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBacktoInTerminalGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbCarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbCarListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbCarListActionPerformed
/**'
 * This button toggles the visibility of the IN and OUT GUI windows and resets the combobox model.
 * @param evt 
 */
    private void btnBacktoInTerminalGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktoInTerminalGUIActionPerformed
        inTerminalGUI.setParkingLotCarList();
        inTerminalGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBacktoInTerminalGUIActionPerformed
    
    /**
     * This button checks to make sure a care is selected if so it calls the unpark method
     * and passes it to it. It also removes the car from the comboBox list and model.
     * @param evt 
     */
    private void btnUnparkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnparkActionPerformed
        if(CbCarList.getSelectedItem() == null){
            alertWindow.output("There are no cars to unpark.");
        } else {    
        Car thisCar = (Car) CbCarList.getSelectedItem();
        unparkCar(thisCar);
        inTerminalGUI.getParkingLotCarList().remove(CbCarList.getSelectedItem());
        CbCarList.removeItem(CbCarList.getSelectedItem());
        }
    }//GEN-LAST:event_btnUnparkActionPerformed
    /**
     * This method calls the inTerminalGUI's unparkCar Method and passes a car object to it.
     * @param car Car
     */
    private final void unparkCar(Car car){
        inTerminalGUI.unparkCar(car);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbCarList;
    private javax.swing.JButton btnBacktoInTerminalGUI;
    private javax.swing.JButton btnUnpark;
    // End of variables declaration//GEN-END:variables
}
